#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.refractored.Resource", IsApplication=false)]

namespace com.refractored
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int pstsDividerColor = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int pstsDividerPadding = 2130771974;
			
			// aapt resource value: 0x7f010003
			public static int pstsDividerWidth = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int pstsIndicatorColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int pstsIndicatorHeight = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public static int pstsPaddingMiddle = 2130771980;
			
			// aapt resource value: 0x7f010008
			public static int pstsScrollOffset = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int pstsShouldExpand = 2130771978;
			
			// aapt resource value: 0x7f010009
			public static int pstsTabBackground = 2130771977;
			
			// aapt resource value: 0x7f010007
			public static int pstsTabPaddingLeftRight = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public static int pstsTextAllCaps = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public static int pstsTextAlpha = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public static int pstsTextColorSelected = 2130771981;
			
			// aapt resource value: 0x7f010010
			public static int pstsTextSelectedStyle = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public static int pstsTextStyle = 2130771983;
			
			// aapt resource value: 0x7f010001
			public static int pstsUnderlineColor = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int pstsUnderlineHeight = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int psts_background_tab_pressed = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int psts_background_tab = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int bold = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int italic = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int normal = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int psts_tab_title = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int psts_tab = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PagerSlidingTabStrip = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 2
			public static int PagerSlidingTabStrip_pstsDividerColor = 2;
			
			// aapt resource value: 6
			public static int PagerSlidingTabStrip_pstsDividerPadding = 6;
			
			// aapt resource value: 3
			public static int PagerSlidingTabStrip_pstsDividerWidth = 3;
			
			// aapt resource value: 0
			public static int PagerSlidingTabStrip_pstsIndicatorColor = 0;
			
			// aapt resource value: 4
			public static int PagerSlidingTabStrip_pstsIndicatorHeight = 4;
			
			// aapt resource value: 12
			public static int PagerSlidingTabStrip_pstsPaddingMiddle = 12;
			
			// aapt resource value: 8
			public static int PagerSlidingTabStrip_pstsScrollOffset = 8;
			
			// aapt resource value: 10
			public static int PagerSlidingTabStrip_pstsShouldExpand = 10;
			
			// aapt resource value: 9
			public static int PagerSlidingTabStrip_pstsTabBackground = 9;
			
			// aapt resource value: 7
			public static int PagerSlidingTabStrip_pstsTabPaddingLeftRight = 7;
			
			// aapt resource value: 11
			public static int PagerSlidingTabStrip_pstsTextAllCaps = 11;
			
			// aapt resource value: 14
			public static int PagerSlidingTabStrip_pstsTextAlpha = 14;
			
			// aapt resource value: 13
			public static int PagerSlidingTabStrip_pstsTextColorSelected = 13;
			
			// aapt resource value: 16
			public static int PagerSlidingTabStrip_pstsTextSelectedStyle = 16;
			
			// aapt resource value: 15
			public static int PagerSlidingTabStrip_pstsTextStyle = 15;
			
			// aapt resource value: 1
			public static int PagerSlidingTabStrip_pstsUnderlineColor = 1;
			
			// aapt resource value: 5
			public static int PagerSlidingTabStrip_pstsUnderlineHeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
